### ISSUE TITLE
Transform: Send Alert

### ISSUE THREAD

**Issue by shindym** [shindym/c10-lnmh-plant-sensors#32]
## Description
- Implementing the sending of Alerts to Botanists/Gardeners if required. 
- Send alert via `SES` or `SNS` - up for discussion.
## Relevant files
- `transform.py`
## User stories
- Part of the Stakeholders requirements, to notify when there is an issue with a plant.

**Comment by luciegamby-sigmalabs** [comment]
Thinking of sending the alerts during the load script? Just because this is where we connect to the database and here we can compare to previous values stored in the database and choose what values are alert-worthy.

**Comment by shindym** [comment]
agreed will be used in load script
