### ISSUE TITLE
Create Github workflow for linting

### ISSUE THREAD

**Issue by shindym** [shindym/c10-lnmh-plant-sensors#6]
Create github workflow:
- Pylint
- Pytest

**Comment by Peritract** [comment]
But why though?

**Comment by aribasyeda** [comment]
This ticket has been updated to create a github workflow just for linting, and not for pytest at this moment in time because the workflow fails as there are currently no tests

**Comment by aribasyeda** [comment]
[Updated]

Create github workflow:

Pylint
